// ###### Introduction & Syntax :

// window.alert("hello"); /* not recommended */
document.write("<span>hello</span>"); // add it to html
console.error("Error");
console.table(["Osama", "Ahmed", "Sayed"]);
console.log("hello \n 'there!!'");
console.log('hello \n "there!!"');
console.log(
  // remember "%c"
  "Hello From %cJS \'%cFile\"",
  "color: red; font-size: 40px",
  "color: blue; font-size: 40px",
);
