// Math Object
// round()
console.log(Math.round(99.2)); // 99
console.log(Math.round(99.5)); // 100

// ceil()
console.log(Math.ceil(99.2)); // 100
console.log(Math.ceil(99.9)); // 100
console.log(Math.ceil(-99.9)); // -99

// floor()
console.log(Math.floor(99.2)); // 99
console.log(Math.floor(99.9)); // 99
console.log(Math.floor(-99.9)); // -100

// trunc()
console.log(Math.trunc(99.5)); // 99
console.log(Math.trunc(-99.5)); // -99

// max() , min()
console.log(Math.min(10, 20, 100, -100, 90)); // -100
console.log(Math.max(10, 20, 100, -100, 90)); // 100

// pow()
console.log(Math.pow(2, 4)); // 16

// random()
console.log(Math.random()); // (random)
